### ISSUE TITLE
LEO Staff logs

### ISSUE THREAD

**Issue by bartusek27** [SnailyCAD/snaily-cadv4#1343] opened 2022-12-23 03:10 UTC
### Describe the feature

Currently AFAIK there is no way to know for commanding officers who has e.g. revoked the license, who accessed what files and when.

It would be great to have some frontend where Police/EMS/FD supervisors would see logs of their officers.

**Comment by Dev-CasperTheGhost** [comment] 2022-12-23 05:32
duplicate of #914. At this time, this is a bit to large for me to handle. I'll see what I can do

**Comment by Dev-CasperTheGhost** [comment] 2022-12-30 17:59
Closing this for now and moving to backlog. I currently don't have the resources to work on this. I'll create a draft issue soon with a long-term solution to this and #914

**Closed by Dev-CasperTheGhost** 2022-12-30 17:59 UTC
Labels: enhancement
