### ISSUE TITLE
LEO whitelisted switch

### ISSUE THREAD

**Issue by Crazy-Zack** [SnailyCAD/snaily-cadv4#330] opened 2022-01-25 04:54 UTC
### Describe the feature

Basically adding an LEO Whitelisted switch, On our server we have Community Officers that are basically allowed to be an LEO before they apply to a different department.

### Additional Context

![image](https://user-images.githubusercontent.com/98304567/150913183-7a900998-ba97-4235-a4c9-feddf9c4653b.png)

**Comment by Dev-CasperTheGhost** [comment] 2022-01-25 08:23
This would be a duplicate of https://github.com/SnailyCAD/snaily-cadv4/issues/274#issuecomment-1013514421?

**Closed by Dev-CasperTheGhost** 2022-01-25 08:23 UTC
Labels: enhancement
