### ISSUE TITLE
activeCallId not clearing when call is closed or when using `911-calls/assign/`

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1438] opened 2023-01-18 17:47 UTC
### What version of Node.js are you using?

N/A

### What version of npm are you using?

N/A

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

v1.44.1 1734eda

### Describe the Bug

When I set a units assignment via 911-calls/assign/{call} it doesn't seem to set activeCallId and in fact active call is still set to a call that is closed.

### Expected Behavior

When assigning a unit to a call via the API, and it may require an additional switch, but it should force the activeCallId to be the one passed via the API.

When assigning a unit to a call and their existing activeCallId is closed, which shouldn't occur anyway, it should override.

The `activeCallId` should always be cleared if the call is ended. However it seems (attached below) the call is not ended when it is automatically closed by the inactivity timer.

### To Reproduce

![image](https://user-images.githubusercontent.com/48030374/213255975-402925c5-8751-4222-8c5e-261aa3d2251a.png)

![image](https://user-images.githubusercontent.com/48030374/213256055-807f2647-7cc3-426e-8e6e-58c6f1ef310e.png)

**Comment by Dev-CasperTheGhost** [comment] 2023-01-18 18:12
Are you seeing any reports in the API logs like: `Failed to set next call id. Skipping...`?

**Comment by Dev-CasperTheGhost** [comment] 2023-01-18 18:13
Note to self:

1. [ ] Allow passing `force` to the API route to force set the `activeCallId`
2. [ ] Investigate the `activeCallId` issue

**Comment by jxckUK** [comment] 2023-01-20 09:48
I haven't experienced this issue again, but I can re-open/reference this issue if it re-appears.

**Comment by Dev-CasperTheGhost** [comment] 2023-01-20 10:29
Yeah, will close this for now then

**Comment by jxckUK** [comment] 2023-01-20 16:44
Unfortunately got this again, my activeCallId is not the only call I'm assigned to that is active:

![image](https://user-images.githubusercontent.com/48030374/213754480-5bf8d746-0f41-4f01-8011-3ae27a4e3f24.png)

![image](https://user-images.githubusercontent.com/48030374/213754615-1e56cb8f-bab3-420c-b3e3-bb47b815fa9b.png)

![image](https://user-images.githubusercontent.com/48030374/213754938-8fcf20c1-49a6-4548-93bf-c95e9f16a1ef.png)

![image](https://user-images.githubusercontent.com/48030374/213755034-42ce2823-90f8-4cd9-90eb-2f62167a74da.png)


Nothing in the logs about failed to set next call ID skipping.

**Comment by jxckUK** [comment] 2023-01-20 17:10
I feel like there's a very high chance this is related to calls that are ended via inactivity because a second user has now reported the same issue (funnily enough the one in the above picture on #6194) and when it ended the activeCallId was not set to null/false.

![image](https://user-images.githubusercontent.com/48030374/213760645-67f0b927-b702-4075-9858-8f54db03eeb1.png)

![image](https://user-images.githubusercontent.com/48030374/213761095-99ad9b98-e798-407c-8a9f-90d8e93d1ba4.png)

See, this call is set to not be ended but it is in the client, which I suspect is the root cause of the problem.

![image](https://user-images.githubusercontent.com/48030374/213761317-33662c3c-e939-49e5-af77-e7b21b756b5e.png)

**Comment by Dev-CasperTheGhost** [comment] 2023-01-20 17:42
I've cleaned up some of the code, so it should be working correctly now. If you're able to update and test, that'd be great! I'm not able to really test this feature :/

**Comment by jxckUK** [comment] 2023-01-20 17:44
Got an update window at 18:45 so can let you know after that. 😄

**Comment by Dev-CasperTheGhost** [comment] 2023-01-20 17:44
sounds good!

**Comment by Dev-CasperTheGhost** [comment] 2023-01-20 17:44
That's UK time right? haha

**Comment by jxckUK** [comment] 2023-01-20 17:51
> That's UK time right? haha
> 
> I'm in GMT+1

Ah yes sorry haha, so 19:45 your time, I'll just post my findings in here and you can pick it up whenever you're next around!

**Comment by Dev-CasperTheGhost** [comment] 2023-01-20 17:52
Yup, no worries haha!

**Comment by Dev-CasperTheGhost** [comment] 2023-01-21 10:52
Were you able to reproduce this on the latest version @jxckUK?

**Comment by jxckUK** [comment] 2023-01-21 11:40
> Were you able to reproduce this on the latest version @jxckUK?

Didn't have any reports of it last night during event, what I'll do quickly though is try and replicate it manually by letting an assigned call expire and then adding another.

**Comment by Dev-CasperTheGhost** [comment] 2023-01-21 11:44
Sounds good, thanks!

**Comment by jxckUK** [comment] 2023-01-21 13:18
Just tested and still the same, call ends via timeout, but does not remove activeCallId

![image](https://user-images.githubusercontent.com/48030374/213868571-8120271d-73f7-45b5-827d-6ffd4c1ef10c.png)


![image](https://user-images.githubusercontent.com/48030374/213868580-f39b7415-e449-4520-bbd9-ec50c66d3e9a.png)


![image](https://user-images.githubusercontent.com/48030374/213868596-94fb0872-8222-4272-9605-929b9a212c04.png)

**Comment by Dev-CasperTheGhost** [comment] 2023-01-21 13:31
So, silly me made a typo - nothing was changed from the previous change. However, should be fixed now :p

**Comment by jxckUK** [comment] 2023-01-21 13:32
It happens! 😄 I'll update and test ASAP but you can close this and I can re-open if you're happy that should fix it.

**Comment by Dev-CasperTheGhost** [comment] 2023-01-21 13:33
will keep open for now, I may setup tests for this specific function, therefore keeping open for now

**Comment by jxckUK** [comment] 2023-01-22 14:58
Seems to have similar issues with incidents too:

![image](https://user-images.githubusercontent.com/48030374/213922608-39b8da24-e38e-4d0f-b3b4-6603e5fea26b.png)

![image](https://user-images.githubusercontent.com/48030374/213922628-a0d8b75c-40eb-413e-b686-c804b3471a54.png)

**Comment by Dev-CasperTheGhost** [comment] 2023-01-22 15:52
So, this is still an issue for both calls and incidents?

**Comment by jxckUK** [comment] 2023-01-22 18:03
For incidents at least, will perform same re-test for calls.

**Comment by Dev-CasperTheGhost** [comment] 2023-01-23 16:17
All seems to be working fine after some testing locally. Do keep in mind that it may only update after 5 minutes because there's a cooldown on it

**Closed** 2023-01-23 16:18 UTC
Labels: enhancement
