### ISSUE TITLE
Function that some windows like the create 911 call, do not close when you click outside the window with the mouse.

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#1020] opened 2022-08-04 20:44 UTC
### Describe the feature

I would wish that there is a function that certain important windows do not close when someone clicks outside the active window or at least the entered data is preserved.

**Comment by Dev-CasperTheGhost** [comment] 2022-08-05 04:56
Duplicate of #928

**Closed by Dev-CasperTheGhost** 2022-08-05 04:56 UTC
Labels: enhancement
