### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by austinbatter** [SnailyCAD/snaily-cadv4#1930] opened 2024-05-23 05:35 UTC
### What version of Node.js are you using?

v20.13.1.

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

SnailyCADv4

### Describe the Bug

Everytime I start/ run the command in my cmd it says " ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @snailycad/api@1.79.1 start: `pnpm prisma migrate deploy && pnpm prisma generate && node --inspect dist/main.js`"

need help with this asap!
![image](https://github.com/SnailyCAD/snaily-cadv4/assets/170599725/5efb5452-f24e-44d6-ae65-74cf7179f12f)

### Expected Behavior

To start without any issues

```[tasklist]
### Tasks
```

**Comment by Infiniti-Development** [comment] 2024-05-26 23:32
@austinbatter can you send a screenshot of you complete console/log? 
2. is this you first install or an update?

**Comment by casperiv0** [comment] 2024-06-09 14:51
Duplicate of #1926

**Closed by casperiv0** 2024-06-09 14:51 UTC

**Comment by austinbatter** [comment] 2024-06-12 19:54
this is a first install
