### ISSUE TITLE
API crashing after x actions

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1390] opened 2023-01-10 05:33 UTC
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

4.8.0

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/211469520-7fca229b-426c-4666-9f90-aebefc9458df.png)

The CAD keeps going down. The only thing I see is this. Happens at least once a day. So then I simply restart it and its fine again for a few hours.

### Expected Behavior

Continued running.

**Comment by Dev-CasperTheGhost** [comment] 2023-01-10 05:40
does it run out of memory?

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-01-10 05:54
I'm not sure is there a way to tell?

**Comment by Dev-CasperTheGhost** [comment] 2023-01-10 05:54
checking your memory usage? I'm not sure if it's a memory issue though. There's no useful error in that screenshot :/

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-01-10 06:11
Yes it seems the error is always some violation with fines

**Comment by Dev-CasperTheGhost** [comment] 2023-01-10 06:27
No other errors?

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-01-10 08:37
None that I can see but I'll have to just wait until it happens again

**Comment by SunlightKim** [comment] 2023-01-10 08:46
Note: `400 Bad Request` response status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (for example, malformed request syntax, invalid request message framing, or deceptive request routing).

Meaning something goes wrong when a request related to fines happens. In this case, it seems like the CAD receives invalid data. Do you perform anything related to fines at any point in time?

**Comment by Dev-CasperTheGhost** [comment] 2023-01-10 09:13
>Note: 400 Bad Request response status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (for example, malformed request syntax, invalid request message framing, or deceptive request routing).
In your case: Meaning something goes wrong when a request related to fines happens. In this case, it seems like the CAD receives invalid data. Do you perform anything related to fines at any point in time?

The `BadRequest` error gets thrown but then right after that the CAD crashes. The `BadRequest` error is the reason why it crashes because I get the error in Sentry too. There is just no stack trace or any other information to work with.

The error message: `fine_invalidDataReceived` simply means there was an incorrect form value provided. This can be a too large number or too small number of what was defined for the penal code value.

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-01-10 11:39
I've been trying to reproduce it but I cannot =/ gave some fines out and it simply stays. I really dont understand whats happening or why its happening. Very frustrating.

**Comment by Dev-CasperTheGhost** [comment] 2023-01-10 12:20
Will close this for now. Reopen when it happens again. Or when I see it again, I’ll reopen this if needed :)

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-01-14 12:06
CAD went down yet again. Exact same error.
![image](https://user-images.githubusercontent.com/25211271/212470873-d5a1a3c9-432c-4837-8290-c35de21a3b12.png)

**Comment by Dev-CasperTheGhost** [comment] 2023-01-14 14:48
I still haven't been able to reproduce this :/. I'll try some things that could get rid of this

**Comment by Dev-CasperTheGhost** [comment] 2023-01-14 15:03
Changed the logic, it will now only throw 1 error instead of possibly multiple

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-01-14 16:33
uh oh i just updated and i think i broke everything
![image](https://user-images.githubusercontent.com/25211271/212483540-5f848acc-20d7-4816-940e-4edd20304581.png)

**Comment by Dev-CasperTheGhost** [comment] 2023-01-14 16:34
Make sure to run the correct install steps

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-01-14 16:56
> Make sure to run the correct install steps

![image](https://user-images.githubusercontent.com/25211271/212485057-3665727e-5ad9-459a-a06e-2df04cad0b12.png)

**Comment by Dev-CasperTheGhost** [comment] 2023-01-14 16:58
Yeah, just delete that folder. I’ll be unavailable from now though. For further support use the Discord server so others can help :)

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-01-17 00:29
![image](https://user-images.githubusercontent.com/25211271/212784612-2a3041bf-34c1-4d30-9e0d-077b3a989bfd.png)

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-01-17 00:30
I've still got issues where it randomly goes down

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-01-17 03:42
![image](https://user-images.githubusercontent.com/25211271/212805076-8602dfb9-da98-414a-baf8-78b684bca049.png)

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-01-17 04:06
Just installed latest version and its going down immediately now lol

![image](https://user-images.githubusercontent.com/25211271/212807736-2d971a03-755d-468a-9d71-d7ed646f0a6b.png)
![image](https://user-images.githubusercontent.com/25211271/212807792-bee1ca3f-4249-4e8e-820b-4c8381951b42.png)

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-03-08 01:28
![image](https://user-images.githubusercontent.com/25211271/223595764-76414dad-7553-4e2e-b9f7-1d8fa9a392e9.png)

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-03-08 01:29
still crashing whenever someone does something invalid with fines/jailtime

**Comment by Dev-CasperTheGhost** [comment] 2023-03-08 05:56
Will re-open this issue. Like I said before, there may not be much I can do here :/

**Comment by Dev-CasperTheGhost** [comment] 2023-03-08 06:08
Are you able to update to the very latest version, then let me know when this error occurs again. The entire error stack should be logged too, this could make it easier for me to debug this

**Comment by Dev-CasperTheGhost** [comment] 2023-03-08 06:08
@Legacy-TacticalGamingInteractive

**Comment by LazyCalypso** [comment] 2023-03-08 13:36
> That’s already in place, therefore I’m confused as to why this is still happening

Well then we'll have to wait to get the entire error stack, since we don't know exactly what is done right before the error is thrown.

**Comment by Dev-CasperTheGhost** [comment] 2023-03-18 14:23
going to close this since no further issues have been reported here nor in the error reporting system. Please re-open this issue if it does happen again

**Closed by Dev-CasperTheGhost** 2023-03-18 14:23 UTC
Labels: help wanted
