### ISSUE TITLE
Jail Issues

### ISSUE THREAD

**Issue by Crusxde** [SnailyCAD/snaily-cadv4#1950] opened 2024-07-13 19:06 UTC
### What version of Node.js are you using?

1.80.2

### What operating system are you using?

Ubuntu

### What version of SnailyCAD are you currently using?

1.80.2

### Describe the Bug

it will not release them from jail even after the timer has been completed, it has been 2 weeks and the only way to remove it is to delete the arrest report. 

![cadissue](https://github.com/user-attachments/assets/93e7c7bb-3f02-451e-a1ac-1513d3fc6139)

### Expected Behavior

For the red to disappear after the timer has completed.

**Comment by casperiv0** [comment] 2024-07-28 06:39
Duplicate of #1902

**Closed by casperiv0** 2024-07-28 06:39 UTC

**Comment by Legacy-TacticalGamingInteractive** [comment] 2025-01-10 08:37
This issue is back again with many people complaining about it :(
Perhaps the best way to fix is to add a Release all from jail option or something like a Search field on the Jail page.
