### ISSUE TITLE
Ability to have multiple roles for CAD permissions

### ISSUE THREAD

**Issue by Dalrae1** [SnailyCAD/snaily-cadv4#567] opened 2022-04-02 12:50 UTC
### Describe the feature

Instead of having a single role be for, say, dispatch, having the option to add multiple roles would be very nice.
![image](https://user-images.githubusercontent.com/52721173/161384129-fb520850-6a45-4d46-a26a-792a2485469e.png)

### Additional Context

https://discord.com/channels/792479048457912360/896327451964223498/959799858284351580

**Comment by Dev-CasperTheGhost** [comment] 2022-04-02 12:52
This is a duplicate of #530. See https://github.com/SnailyCAD/snaily-cadv4/issues/530#issuecomment-1069317549

**Comment by Dalrae1** [comment] 2022-04-02 12:59
I see. I still do think it's a good idea because many people customize their Discord guilds vastly different than having a single role for each department, dispatch, admin, etc (Usually to separate different permissionsets) and many server owners want each member to have as few roles as possible for simplicity's sake

**Closed** 2022-04-03 08:02 UTC
Labels: enhancement
