### ISSUE TITLE
Draggable & Minimizable Modals 

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1469] opened 2023-01-25 17:51 UTC
### Describe the feature

I'm not sure if this is possible but one of our members requested the following:

> when doing a name or vehicle search, can there be an ability to minimise the windows instead of having to close them each time. So when doing a name search, you then have to close that window and then do a vehicle search. You sometimes forget the name and have to ask for ID again then close the vehicle search window and do a new name search. Could there be an ability to have the two open at the same time, and minimise one or the other instead of having to close one or the other on each occasion.
> 
> If you forget to close one of the windows and try to open another one, i.e i have a name search window open and go to open another, a message comes up informing there is already a window open.

Something like the attached additional content gif I believe is what the ask is. This would be for the following modals:

- Name Search
- Registration Search
- Creating warrants/warnings/arrest reports and fines.

### Additional Context

[![image](https://user-images.githubusercontent.com/48030374/214642748-8520f06e-8e7c-4d96-a8be-3b16a390bb16.png)](https://docs.telerik.com/blazor-ui/knowledge-base/images/window-big-screen.gif)

**Comment by Dev-CasperTheGhost** [comment] 2023-01-25 17:52
Duplicate of #1167

**Closed by Dev-CasperTheGhost** 2023-01-25 17:52 UTC
Labels: enhancement
