### ISSUE TITLE
[BUG] - Roles break if Discord Authentication is enabled

### ISSUE THREAD

**Issue by pp2amd6** [SnailyCAD/snaily-cadv4#649] opened 2022-04-22 18:28 UTC
### What version of Node.js are you using?

does not matter

### What version of npm are you using?

does not matter

### What operating system are you using?

does not matter

### What version of SnailyCAD are you currently using?

v1.0.0-beta.87

### Describe the Bug

So.

CAD settings:
- "CAD Whitelist" disabled
- "Allow users to authenticate with Discord" enabled
- "Allow username/password login" disabled

There is a user with Discord rights
![image](https://user-images.githubusercontent.com/4976837/164770974-1e7015e6-16e3-483a-ab82-4587eaec8f9a.png)

Role settings in CAD are as follows
![image](https://user-images.githubusercontent.com/4976837/164771739-eb27091c-0498-4a46-b994-2473ab8604a4.png)

When I enable ALL rights for the user and save them, after reloading the page, the user sees ALL items according to the rights.
But when he visits one of the pages, for example, "unit management", he gets a "Forbidden" error and all rights are disabled (he have only LEO right). See video bellow.

https://user-images.githubusercontent.com/4976837/164772629-b5b38fa4-5c94-44ea-aeb7-3b13ff355fca.mp4

This is a **critical bug**, because other users from the administration will not be able to work normally.

### Expected Behavior

I expect everything to work correctly :)

**Comment by Dev-CasperTheGhost** [comment] 2022-04-22 18:53
> This is a critical bug, because other users from the administration will not be able to work normally.

if it is extremely critical, I’d recommend you disable the feature. I’m not home for the weekend so won’t be able to fully fix some of the issues. Sorry for the inconvenience!

**Comment by Dev-CasperTheGhost** [comment] 2022-04-23 11:57
I'm unable to reproduce this error with the exact same information.

**Comment by Dev-CasperTheGhost** [comment] 2022-04-23 11:58
Can you update the CAD to the latest version?

**Comment by pp2amd6** [comment] 2022-04-23 13:20
> Can you update the CAD to the latest version?

Local git repo up to date.
CAD updated.

The problem recurred, now when you try to open the Live Map page.

@Dev-CasperTheGhost  Can I somehow provide logs or something else?

**Comment by Dev-CasperTheGhost** [comment] 2022-04-23 13:21
I'm not sure. I'll try again tomorrow

**Comment by Dev-CasperTheGhost** [comment] 2022-04-24 06:50
Does it happen all the time? Or only every so often @pp2amd6

**Comment by pp2amd6** [comment] 2022-04-24 07:34
It is hard to say.
This happens on different pages in different ways.
The user may lose the rights when he opens the "Manage Units" page. I give him admin rights again and he can open the "Manage units" page without problems, but he loses the rights when he opens the "Live map" page and so on.

I can ask the user to record a video of how it happens and record a video from my side.

**Comment by pp2amd6** [comment] 2022-04-24 18:06
@Dev-CasperTheGhost can you reopen this bug because the problem is still there?

**Comment by Dev-CasperTheGhost** [comment] 2022-04-24 18:08
yeah, sure. I wasn't able to take another look today, sorry. 

> I can ask the user to record a video of how it happens and record a video from my side.


This may be helpful yeah!

**Comment by Dev-CasperTheGhost** [comment] 2022-04-24 18:48
Okay, this should be fixed now actually @pp2amd6. If not, let me know!

**Closed** 2022-04-24 18:47 UTC
Labels: bug
