### ISSUE TITLE
BUG cannot type in arrest reports

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1528] opened 2023-02-14 22:36 UTC
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.47.0 3ddd301

### Describe the Bug

![image](https://user-images.githubusercontent.com/25211271/218878801-e0ddcb01-25bb-41fa-b10e-086759a26cf4.png)

### Expected Behavior

To be able to type in arrest reports etc

**Comment by Dev-CasperTheGhost** [comment] 2023-02-14 23:10
Can you provide some more information here?

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-02-15 00:09
Not  much else to say. When I go to Dashboard then I go to Create Ticket it does not let me type anything in I cannot click or type

**Comment by Dev-CasperTheGhost** [comment] 2023-02-15 05:53
I'm unable to reproduce this issue on my test-cad and yours: 
![image](https://user-images.githubusercontent.com/53900565/218944353-00389c88-2a38-44eb-afed-b7181af2a534.png)

**Comment by Dev-CasperTheGhost** [comment] 2023-02-15 05:55
@Legacy-TacticalGamingInteractive what browser is this? Are you also able to provide a video reproduction of this, please?

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-02-15 06:18
using chrome 
![image](https://user-images.githubusercontent.com/25211271/218948007-9717396e-b6a2-4f6b-b8fd-e374f3fb68c9.png)


but its not just in browser its also in the game tablet (iframe we use) and multiple people have been complaining about this issue

**Comment by Dev-CasperTheGhost** [comment] 2023-02-15 06:19
Are you able to send a video reproduction of this? Also better describe the issue so I could possibly reproduce it and fix this

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-02-15 06:20
https://user-images.githubusercontent.com/25211271/218948444-4889364b-a554-44c0-b66a-711eb86f71e2.mp4

**Comment by Dev-CasperTheGhost** [comment] 2023-02-15 06:23
Perfect, this seems to be a chrome only issue. I Will only be able to fix this later today unfortunately. 

Page refreshes do not temporarily fix this issue?

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-02-15 06:35
Refreshing does not help :(

**Comment by Dev-CasperTheGhost** [comment] 2023-02-15 13:51
Fixed now, make sure to update your SnailyCAD instance!

**Comment by Dev-CasperTheGhost** [comment] 2023-02-15 13:53
nvm - another issue came up with this :/

**Comment by Dev-CasperTheGhost** [comment] 2023-02-15 14:59
@Legacy-TacticalGamingInteractive this is fully fixed now! Make sure to update your SnailyCAD instance!

**Closed** 2023-02-15 14:58 UTC
Labels: bug
