### ISSUE TITLE
Bug/Feature: Saving Changes needs an automatic page Reload

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1719] opened 2023-07-02 01:41 UTC
### Describe the feature

I noticed when saving values that the page does not automatically refresh/reload.

Would it be possible to add this? So that the changes save properly in succession.

### Additional Context

I tried editing multiple 10 codes but only the changes of the first one I edited saved. I wasted 30 minutes. The only way to properly do multiple values is to manually refresh the page after every single edit otherwise it will not change anything you edit after the first one.

**Comment by Dev-CasperTheGhost** [comment] 2023-07-03 09:04
I'm unable to reproduce this. Are you able to send a video reproduction? @Legacy-TacticalGamingInteractive

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-07-03 09:27
Note: Relating to Department Permissions specifically on 10 Codes page to reproduce.

**Comment by Dev-CasperTheGhost** [comment] 2023-07-04 07:07
Closing this for since not able to reproduce. Further communication via Discord for this bug

**Closed by Dev-CasperTheGhost** 2023-07-04 07:07 UTC
Labels: 🐛 bug
