### ISSUE TITLE
Selecting a custom 'off duty' status results in an error

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#187] opened 2021-12-24 11:22 UTC
### What version of Node.js are you using?

16.13.1

### What version of npm are you using?

8.3.0

### What operating system are you using?

 Linux (ubuntu 20.04)

### Describe the Bug

When it is triggered it gives the error message and doesn't run any Discord hook pushes but it does actually change the status requiring a refresh of the page to show the change.

![image](https://user-images.githubusercontent.com/48030374/147348490-b33c037f-2fa5-46e8-bb25-e090f0d6f5b8.png)

```
DEBUG:
data: "{\"status\":\"c4835ec7-7c5d-4b81-95b6-998fe0917c3c\"}"
message: "Request failed with status code 500"
method: "put"
response:
config: {transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …}
data: "InternalServerError"
headers:
content-length: "19"
content-type: "application/json; charset=utf-8"
[[Prototype]]: Object
request: XMLHttpRequest
onabort: ƒ ()
onerror: ƒ ()
onload: null
onloadend: ƒ T()
onloadstart: null
onprogress: null
onreadystatechange: null
ontimeout: ƒ ()
readyState: 4
response: "InternalServerError"
responseText: "InternalServerError"
responseType: ""
responseURL: "http://URLREMOVED:8080/v1/dispatch/status/ckxjnerrw6634s41hyhbzi8uz"
responseXML: null
status: 500
statusText: "Internal Server Error"
timeout: 0
```

### Expected Behavior

Once this state is pressed I expected the LEO panel to return back to its original state allowing for the user to return on duty when required. I also expected the integration with Discord to send a hook message informing of a status update.

### To Reproduce

Create a custom state code and set the action to off duty, trigger the state code and it should re-produce this issue.

**Comment by Dev-CasperTheGhost** [comment] 2021-12-25 11:48
This may have been a duplicate of #186. Are you able to verify it it works now? I cannot reproduce this error

**Comment by jxckUK** [comment] 2021-12-25 12:01
> This may have been a duplicate of #186. Are you able to verify it it works now? I cannot reproduce this error

Just updated and re-built and can confirm it's all fixed! Thanks Casper & happy holidays!

**Closed** 2021-12-25 12:19 UTC
Labels: bug
