### ISSUE TITLE
Merged units disappear at times

### ISSUE THREAD

**Issue by ALamX** [SnailyCAD/snaily-cadv4#1460] opened 2023-01-23 11:55 UTC
### What version of Node.js are you using?

latest

### What version of npm are you using?

latest

### What operating system are you using?

Windows

### What version of SnailyCAD are you currently using?

1.44.6

### Describe the Bug

When assigning a merged unit to a call, or refreshing the dispatch dashboard, merged units disappear from the active officers tab.

### Expected Behavior

Merged units should stay visible, along with their status

### To Reproduce

Assign a merged unit to a call, or refresh the dispatch dashboard

**Comment by Dev-CasperTheGhost** [comment] 2023-01-23 15:15
How many officers were active when this happens? I'm unable to reproduce this

**Comment by ALamX** [comment] 2023-01-23 16:22
Was not able to replicate by assigning, but was able to replicate by refreshing the page. There were three active units (of wich two were paired) After refreshing i only saw the non-paired unit

**Comment by ALamX** [comment] 2023-01-23 16:23
And now no longer able to replicate

**Comment by Dev-CasperTheGhost** [comment] 2023-01-23 16:24
Could've been a browser issue. Closing for now since I have not be able to reproduce after multiple tries.

**Closed by Dev-CasperTheGhost** 2023-01-23 16:24 UTC
Labels: bug
