### ISSUE TITLE
Password Reset Option

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1498] opened 2023-01-30 20:40 UTC
### Describe the feature

We have tickets every day opening because someone forgot their stupid password lol. This would be a great feature to have on auth page.

**Comment by Dev-CasperTheGhost** [comment] 2023-01-31 06:04
Duplicate of #1276

**Comment by Dev-CasperTheGhost** [comment] 2023-01-31 06:04
Will keep this one open then for now. Can't promise any solution at this time.

**Comment by jxckUK** [comment] 2023-01-31 12:56
Instead of email, could you do some security question implementation? Optional feature of course as it comes with downsides but that may be a suitable alternative?

**Comment by Local9** [comment] 2023-01-31 14:03
Personally wouldn't want a persons email, this brings with it more data protection requirements like the GDPR for example given EU Citizens, not something I personally want to deal with but others maybe fine with. A Discord Bot process maybe or adding a permission that allows passwords to be changed by an Admin could be a better idea.

**Comment by Dev-CasperTheGhost** [comment] 2023-01-31 14:06
>  or adding a permission that allows passwords to be changed by an Admin could be a better idea.

This is already possible.

**Comment by Dev-CasperTheGhost** [comment] 2023-01-31 14:07
> Personally wouldn't want a persons email, this brings with it more data protection requirements like the GDPR for example given EU Citizens, not something I personally want to deal with but others maybe fine with.

100% agree with this. That's what I stated in the original issue too.

> Instead of email, could you do some security question implementation? Optional feature of course as it comes with downsides but that may be a suitable alternative?

This isn't a good solution either because they will forget this too in the long run?

**Comment by WhitigolProd** [comment] 2023-01-31 14:11
> This isn't a good solution either because they will forget this too in the long run?

I'd have to agree with this, everyone forgets security questions. Maybe when signing up, they're given some sort of backup key, which they can enter to recover their account and change their password? Then when they change it they're given a new backup key.

**Comment by Dev-CasperTheGhost** [comment] 2023-01-31 14:12
But they'd still loose that key too? If they don't save their passwords properly, they would loose that key too.

**Comment by Local9** [comment] 2023-01-31 14:14
> > or adding a permission that allows passwords to be changed by an Admin could be a better idea.
> 
> This is already possible.

If its already possible, then its a mute issue. If its about putting in a request to reset a password where the don't have to go about asking some one, then adding something to a Discord Bot process could be a better idea for automation of it. There is no perfect solution to this.

**Comment by WhitigolProd** [comment] 2023-01-31 14:16
> adding something to a Discord Bot

Could agree with this, but not all communities would be making use of a Discord Bot. A security key _could_ be sent in the form of a file. But regardless, would risk the possibility of losing it. But at that point, would it not just be easier to reach out to someone to request a password reset?

**Comment by Creizy** [comment] 2023-01-31 14:27
Can't they just login without using password through Discord/Steam oAuth?

**Comment by jxckUK** [comment] 2023-01-31 14:27
> This isn't a good solution either because they will forget this too in the long run? @jxckUK

Yeah I guess so, but this is the industry standard for password reset options outside of emailing links (Microsoft etc still use this as a valid SSPR route). It's the best option to provide *some* ability to reset your own credentials. If people forget both there's not a lot other than an administrator dealing with a password reset that can be done.

**Comment by Local9** [comment] 2023-01-31 14:28
> > adding something to a Discord Bot
> 
> Could agree with this, but not all communities would be making use of a Discord Bot. A security key _could_ be sent in the form of a file. But regardless, would risk the possibility of losing it. But at that point, would it not just be easier to reach out to someone to request a password reset?

That still means its a mute issue right? there is already a process to reset a password which requires communicating with a user that has the permission (this reminds me of work too much with Microsoft password resets 🤣).

Granted, not all communities will use Discord but you still require some way of knowing who it is thats requested the reset and what user to apply it to via the only two known means at the moment, Steam or Discord. This feature could be an exculsive feature which is only there for users of the Discord bot? but wouldn't be great I feel, it could come across as favouritism.

If they authed with Discord or Steam, again this a mute issue as the account is linked with those Auths, so its only those who don't have a way of knowing who that user is and security questions could be a process but that still raises a lot of its own issues.

**Comment by Local9** [comment] 2023-01-31 14:32
> Can't they just login without using password through Discord/Steam oAuth?

That defeats the point of the issue, if they were using oAuth this wouldn't be a problem. Maybe making oAuth the preffered account creation method is a better solution but this would be down to the owner to add in all the required information for oAuth, something many I doubt will do.

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-02-01 19:12
A lot of times people login with Steam then cannot get back into the Discord either. Its irritating. But as SnailyCAD grows this problem will increase on many communities. Its literally a daily problem almost for us.

**Comment by Dev-CasperTheGhost** [comment] 2023-02-02 05:58
I agree @Legacy-TacticalGamingInteractive, there is just no *good* solution to this?

> A lot of times people login with Steam then cannot get back into the Discord either. 

Disable Steam oauth, and just keep it to Discord oauth?

> discord bot

I think this could be used, but how could I verify the user. Any user could request a password change for a given username?

> Security questions

I think this could be the most correct option for now. Require a user to set 3 security questions after registration and allow them the change it in the account settings

**Comment by Local9** [comment] 2023-02-02 12:24
> I think this could be used, but how could I verify the user. Any user could request a password change for a given username?

Personally my thought was only with those who have their Discord ID added to their SnailyCAD User, so that does put a spanner in the works for those who don't, else you can combine the Security Questions into it also with DMs to the Bot.

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-02-10 20:31
![image](https://user-images.githubusercontent.com/25211271/218191660-ca073a23-a22e-4386-a992-63a1a3585c87.png)



Please. Kill. Me.

Every. Time.

Going to disable Steam auth.

**Comment by Dev-CasperTheGhost** [comment] 2023-02-10 20:31
if they authenticated via Steam, there is no password set. They must set a password for their account

**Comment by WhitigolProd** [comment] 2023-02-10 21:01
> if they authenticated via Steam, there is no password set. They must set a password for their account

Maybe it would be better to have a password required during registration, then to link Steam or Discord optionally during the registration process as well?

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-02-10 21:26
Agreed 90% of people who logged in with Steam or Discord cannot get back into their accounts afterwards

**Comment by WhitigolProd** [comment] 2023-02-10 21:27
> Agreed 90% of people who logged in with Steam or Discord cannot get back into their accounts afterwards. Probably a user error but still.

Yeah, and being inside an iframe in game, not sure about steam auth, but I know discord auth won't work regardless, so password would be required.

**Comment by Dev-CasperTheGhost** [comment] 2023-02-11 07:09
> Maybe it would be better to have a password required during registration, then to link Steam or Discord optionally during the registration process as well?

Make sure to update your SnailyCAD instance, but this is now supported:

1. Disable `Steam OAuth` and `Discord Oauth`
2. Enable `Force Steam Auth` and `Force Discord Auth`
3. Done

This will not allow a new user to create an account via an oauth provider, however, it will require them to sync those oauth providers to their CAD account after the account is created.

cc @Legacy-TacticalGamingInteractive @WhitigolProd

**Comment by Legacy-TacticalGamingInteractive** [comment] 2023-03-29 13:51
SUGGESTION:

Password Prompt with Discord authentication. As a backup measure.

So when someone logs in via Discord authentication (or Steam I guess) it will pop up a message saying they must set a password as a backup option in case they lose access to their Discord or Steam. Or, if they forget because they are an idiot that they originally logged in with Discord or Steam and thats why they don't have a username or password lol.

**Comment by Dev-CasperTheGhost** [comment] 2023-03-29 15:41
Yah, this could work, similar to `Force Discord/Steam Auth`. This could be `Force Account Password`. This will require a user to set a password if they don't already

**Closed** 2023-03-29 17:39 UTC
Labels: enhancement
