### ISSUE TITLE
The strike of desync is back + some minor page load issues. 

### ISSUE THREAD

**Issue by Caleb-J773** [SnailyCAD/snaily-cadv4#1306] opened 2022-12-10 01:36 UTC
### What version of Node.js are you using?

v18.12.1

### What version of npm are you using?

8.19.2

### What operating system are you using?

Ubuntu 22.04.1 LTS x86_64

### What version of SnailyCAD are you currently using?

Latest 1.36.0+

### Describe the Bug

Noticed an issue with another possible desync issue with the CAD. The last update that fixed the desync was working great, and still has been working fine, however I have noticed that it still desyncs a bit when **assigning calls to units (tested fire/EMS) and also when units set statuses.**  - `Dispatcher View
`
Hopefully the issue is similar to the other one and that it should be a similar fix but I'm not sure heh!

The other bug, this has only started happening just recently, not sure if it's new update related, **but my pages tend to hang sometimes.** 
Example: `Visiting another page on the CAD causes it to not load anything and remains stuck on the previous page. `

Doesn't happen a lot of times and seems to have more often in the admin panel's settings.

I've checked my proxy config and I hadn't changed anything around and nothing new server config wise either. So I'm not sure.

### Expected Behavior

Should be properly synced and pages shouldn't get stuck on loading.

### To Reproduce

Have two people on, one person as a unit for FD/EMS and another as dispatcher, after a while the same issue like the last desync problem will happen, in this case, the status and or when on a call won't show up properly until the page is reloaded

I'm guessing this is some sort of socket disconnect like the last issue?

In terms of the page loading issue, that seems to have more often, mostly in the admin panel when switching to different settings management and manage units.

**The page load issue is rather minor.**

**Comment by Dev-CasperTheGhost** [comment] 2022-12-10 06:54
> The other bug, this has only started happening just recently, not sure if it's new update related, but my pages tend to hang sometimes.
Example: Visiting another page on the CAD causes it to not load anything and remains stuck on the previous page.

have seen this before too, not locally though. What pages, do you know?

**Comment by GamingFlamin** [comment] 2022-12-10 07:21
> have seen this before too, not locally though. What pages, do you know?
More reliably, I've gotten it to do a lot when it came to managing users page and clicking the button for "**manage**" to manage the perms. 

Other times randomly would be clicking around the admin panel then trying to switch to let's say dispatch dashboard. 

And another, from Manage Users > Manage Units/citizens and so on. 

The page URL does load the path, admin/manage/citizens
but doesn't load the page.

**Comment by GamingFlamin** [comment] 2022-12-10 08:51
May have found something, 
![image](https://user-images.githubusercontent.com/4467576/206841934-f307737a-ee52-4729-ae47-253da6e8beea.png)
Saw this in my browser's console when attempting to load a page that got stuck again.

**Comment by Dev-CasperTheGhost** [comment] 2022-12-10 08:51
yeah, that's the error from a module, I have seen that before too. I'm not sure where it comes from nor is there a fix. So the issue will probably stay for now

**Comment by GamingFlamin** [comment] 2022-12-10 08:52
Ah alright, yea it's not a major issue, a good refresh fixes the issue. 

In terms of the sync? It seems rather minor, but I assume maybe it's similar to the other issue that happened with the socket disconnection?

**Comment by Dev-CasperTheGhost** [comment] 2022-12-10 08:53
no, this would be a different issue. I have not identified it yet

**Comment by GamingFlamin** [comment] 2022-12-10 08:56
Alright, yea I'll keep you updated if I notice anything else misbehaving but I mean everything else seems to be syncing well and working great, it's just the status and the little tab for each unit that shows what call is assigned to the unit doesn't show the new change until a page reloads

(Though suspiciously like the other issues, these two are completely random and can work perfectly fine for a good bit then just stop.)

**Comment by Dev-CasperTheGhost** [comment] 2022-12-12 10:30
when the Socket sync stops syncing, can you check the network tab and see if there are any connection closed errors, here's an example in FireFox: 
![image](https://user-images.githubusercontent.com/53900565/207023034-9c6f0395-990b-4b12-b0d9-b6ea9b8b1275.png)

After some time, I was able to reproduce this error code, but haven't found any fixes yet.

**Closed as completed** 2022-12-12 14:44 UTC
