### ISSUE TITLE
Manage Settings Creates Error

### ISSUE THREAD

**Issue by nick-perry14** [SnailyCAD/snaily-cadv4#588] opened 2022-04-08 21:06 UTC
### What version of Node.js are you using?

Latest

### What operating system are you using?

Ubuntu

### Describe the Bug

When opening the cad settings, the following screen appears (after recent update)
![image](https://user-images.githubusercontent.com/6935777/162530643-ab8b565e-c83f-4052-a52e-a33b5c55e14d.png)

### Expected Behavior

Cad settings should appear

**Comment by Dev-CasperTheGhost** [comment] 2022-04-09 06:00
@nick-perry14 I'm unable to reproduce this error. What action did you perform, and are you able to provide a screenshot of the error in the browser console?

**Comment by nick-perry14** [comment] 2022-04-09 06:14
![image](https://user-images.githubusercontent.com/6935777/162559223-bd88f752-6436-4901-bbd6-be169c521bf6.png)

Admin -> Cad settings

**Comment by Dev-CasperTheGhost** [comment] 2022-04-09 06:18
Should be fixed now

**Closed** 2022-04-09 06:18 UTC
Labels: bug
